[package]
name = "my-bin-crate"
version = "0.1.0"
authors = ["Maximilian Köstler <maximilian@koestler.hamburg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
draw = { path = "../draw" }
print = { path = "../print" }
skycolor = { path = "../skycolor" }
